services:
  backend:
    build: ./backend/petshop
    ports: 
      - "3030:3030"
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - ./backend/petshop/src:/app/src

  frontend:
    build: ./frontend/petshop
    ports: 
      - "3002:3000"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend/petshop/src:/app/src

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: 
      - "27017:27017"
    volumes:
      - ./data/dump:/dump
      - ./data/import.sh:/docker-entrypoint-initdb.d/import.sh


